// shows a single note object 
// like the Model in MVC
class Note {
  // id of the note and is automatically generated by the db
  // ? means that the id is nullable
  int? id;
  
  // what's actually in the note
  String content;


 Note({
  this.id,
  // required because the note must have something in it
  required this.content,
 });


/*
e.g. map <-----> note


{
  'id': 1,
  'content': 'hello'
}


Note (
  id: 1,
  content: 'hello'
)
*/


// convert map -> note to store in db
// so that we can read the data from the db
factory Note.fromMap(Map<String, dynamic> map) {
  return Note (
    id: map['id'] as int,
    content: map['content'] as String,
    
  );
}

// convert note -> map to store in db
// so that we can write the data to the db
Map<String, dynamic> toMap() {
  return {
    // no need to return the id because it's automatically generates the id
    'content': content,
  };
}
}